### ISSUE TITLE
Can't save as PDF or SVG, missing dependencies ?

### ISSUE THREAD

**Issue by pkofod** [sisl/PGFPlots.jl#22]
I can save my plot (for example the first plot in the documentation) as a TEX file, and compile it just fine, but when I try to save it as PDF or SVG, I get the message

```
save("plots.pdf", a)
! Undefined control sequence.
\pgfplots@LUA@survey@start ...{\pgfutil@directlua 
                                                  {tex.sprint(\pgfplotsHASH ...
l.17 };
     
ERROR: LaTeX error
 in save at /home/pkm/.julia/v0.4/TikzPictures/src/TikzPictures.jl:165
 in save at /home/pkm/.julia/v0.4/PGFPlots/src/PGFPlots.jl:583
```

Any idea what this might be? Is there a dependency I need, which is not listed in the documentations?

**Comment by mykelk** [comment]
The dependencies should be listed in the documentation. Can you send me the command that resulted in this?

**Comment by pkofod** [comment]
Hm it seems to be a luatex-problem. I use
```
using PGFPlots
x = [1,2,3]
y = [2,3,4].^5
a = plot(x, y)
save("myplot.svg", a)
```

to generate

```
\documentclass[tikz]{standalone}
\usepackage{pgfplots}
\pgfplotsset{compat=newest}
\pgfplotsset{every axis legend/.append style={%
cells={anchor=west}}
}
\usepgfplotslibrary{polar}
\usetikzlibrary{arrows}
\tikzset{>=stealth'}

\begin{document}
\begin{tikzpicture}[]
\begin{axis}[view = {{0}{90}}]\addplot+ coordinates {
(1, 32)
(2, 243)
(3, 1024)
};
\end{axis}

\end{tikzpicture}
\end{document}
```
which compiles in `pdflatex` but not in `luatex`.

**Comment by mykelk** [comment]
Yeah, it works on my machine as well as on JuliaBox. I have tested on TexLive 2014 and 2015. If on Ubuntu, I've had good luck with [this script](https://github.com/scottkosty/install-tl-ubuntu) to get it installed in a way so that tlmgr can update the various packages like pgfplots. I have pgfplots 1.12.1. Luatex doesn't work for me. Lualatex does. You can switch between lualatex and pdflatex using the `tikzCommand` in TikzPictures.jl.

**Comment by mykelk** [comment]
It has been tested on v1.10 and 1.12. Make sure that you use lualatex (which should be the default) and not luatex.
