### ISSUE TITLE
Bar charts

### ISSUE THREAD

**Issue by mykelk** [sisl/PGFPlots.jl#57]
It would be nice to support bar charts with symbolic data. What would be a nice API for this?

**Comment by tawheeler** [comment]
Do you mean it should figure out how to handle non-integer data, such as an array of Strings?

Something like `Plots.Bar(data, labels=map(string, sort!(unique(data)))`?

This is probably a straightforward application of the CategoricalDiscretizer.

```
data = [:cat, :dog, :dog, :cat, :cat, :elephant]
catdisc = CategoricalDiscretizer(data)
encode(catdisc, data) # outputs  [1,2,2,1,1,3]
```

**Comment by tawheeler** [comment]
So it seems that simply converting to integer values and outputing something like:
```
\begin{tikzpicture}
\begin{axis}
\addplot+[ybar] plot coordinates
	{(0,3) (1,2) (2,4) (3,1) (4,2)};
\end{axis}
\end{tikzpicture}
```
![image](https://cloud.githubusercontent.com/assets/3334079/19692143/1b9dc018-9ad7-11e6-8c51-2e170640abce.png)


is insufficient, as the axis will then have {0...N} instead of the symbol values.

We can instead use symbolic coords, something along the lines of:

```
\begin{tikzpicture}
  \begin{axis}[
  	title=Uses lowest $x$ coords for xmin,
    xbar,
    width=12cm, height=3.5cm, enlarge y limits=0.5,
    xlabel={\#participants},
    symbolic y coords={no,yes},
    ytick=data,
    nodes near coords, nodes near coords align={horizontal},
    ]
    \addplot coordinates {(1,no) (9,yes)};
  \end{axis}
\end{tikzpicture}
```
![image](https://cloud.githubusercontent.com/assets/3334079/19692148/22e5a5c0-9ad7-11e6-8107-2cda2925c923.png)

**Comment by mykelk** [comment]
Yeah, we should think about this. I think we want to support both symbol as well as string data. The coordinates that you provide in the latex do not have to correspond to the text---just the labels.
