### ISSUE TITLE
install error  about VideIO

### ISSUE THREAD

**Issue by nizhizhen** [sisl/PGFPlots.jl#80]
![2017-09-01 20-06-01](https://user-images.githubusercontent.com/19453340/29974337-0c64908a-8f65-11e7-8f0b-6300148efa22.png)

**Comment by mykelk** [comment]
Fortunately, that build error doesn't affect PGFPlots.jl. It comes from the dependency on Reel.jl.

Perhaps we can just remove the dependency on Reel? We'll need it under `test/REQUIRE` so that we can run the test that involves Reel. I think we would also need to add this line to the documentation notebook:
```julia
extension(m::MIME"image/svg+xml") = "svg"
```
Right, @tawheeler ?

**Comment by tawheeler** [comment]
Reel feels more like an optional add-on. Will do
