### ISSUE TITLE
Combining Image with Contour

### ISSUE THREAD

**Issue by jdonnert** [sisl/PGFPlots.jl#95]
Hi, 

I need to overlay Contour lines onto an Image in a 2D plot. Unfortunately, simply including both into a single Axis produces a 3D plot.  Is there another way to make this happen ? 

Thank you for your help.

Julius

```
using PGFPlots

f     = (x,y)->x*exp(-x^2-y^2)
img = Plots.Image(f, (-2,2), (-2,2))
con = Plots.Contour(f, (-2,2), (-2,2))
ax   = PGFPlots.Axis([img, con])
PGFPlots.save("./test.pdf", ax)
```

<img width="329" alt="screen shot 2018-06-03 at 21 33 55" src="https://user-images.githubusercontent.com/5123958/40890409-d6afb9c6-6775-11e8-9e28-bcd55fd17e45.png">

**Comment by mykelk** [comment]
It looks like it isn't detecting that the view should be from above for the contour. You can set it like this:
![image](https://user-images.githubusercontent.com/6294079/40897665-2786786c-6771-11e8-8b8f-1607ed716503.png)
The contours aren't showing up properly, but you can see the labels. You can see the commands I used to prevent the tex from being deleted from the current directory so that you can inspect the tex source and try to fix it. If you can figure out how to show the contour labels correctly in tex, let me know and I (or someone) can fix our Julia package.
